'use strict'

// Six tiny, REAL, browser-playable media fixtures — one per renderable format
// (D1). Verified in headless Chrome during authoring: loadedmetadata fired,
// durations/dimensions were correct, and playbackRate 3 took. They are base64'd
// here because the repo avoids committed binaries (text in git, like the image
// buffers imagemeta.test.js builds in-test). Regenerate with ffmpeg:
//
//   ffmpeg -y -f lavfi -i color=c=0xeb4a26:s=64x48:d=1:r=8 -c:v libx264 -profile:v baseline -pix_fmt yuv420p -movflags +faststart tiny.mp4   # 64x48, 1.0s
//   ffmpeg -y -f lavfi -i color=c=0x2e6fd8:s=64x48:d=1:r=8 -c:v libvpx -b:v 30k tiny.webm                                                    # 64x48, 1.0s
//   ffmpeg -y -f lavfi -i sine=frequency=440:duration=1 -ar 8000 -ac 1 -b:a 8k tiny.mp3                                                      # 1.0s
//   ffmpeg -y -f lavfi -i sine=frequency=440:duration=1 -ar 8000 -ac 1 -c:a aac -b:a 16k -movflags +faststart tiny.m4a                       # 1.0s
//   ffmpeg -y -f lavfi -i sine=frequency=440:duration=0.25 -ar 8000 -ac 1 -c:a pcm_u8 tiny.wav                                               # 0.25s
//   ffmpeg -y -f lavfi -i sine=frequency=440:duration=1 -ar 8000 -ac 1 -c:a libvorbis tiny.ogg                                              # ~0.99s
//
// Exact bytes/sizes differ across ffmpeg versions — fine by design: tests assert
// behavior and slice-equality against the SAME generated file, never absolute bytes.

const fs = require('node:fs')
const path = require('node:path')

const FIXTURES = {
	"tiny.mp4":
		"AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAANDbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAA+gAAQAAAQAA" +
		"AAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAA" +
		"Am50cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAA" +
		"AAAAAAAAAAAAAABAAAAAAEAAAAAwAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAAAAAAABAAAAAAHmbWRpYQAAACBtZGhk" +
		"AAAAAAAAAAAAAAAAAABAAAAAQABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAABkW1p" +
		"bmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAAVFzdGJsAAAAuXN0c2QA" +
		"AAAAAAAAAQAAAKlhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAEAAMABIAAAASAAAAAAAAAABFUxhdmM2Mi4xMS4xMDAgbGli" +
		"eDI2NAAAAAAAAAAAAAAAGP//AAAAL2F2Y0MBQsAK/+EAF2dCwArZBHsBEAAAAwAQAAADAQDxImSAAQAFaMuDyyAAAAAQcGFzcAAA" +
		"AAEAAAABAAAAFGJ0cnQAAAAAAAAW2AAAAAAAAAAYc3R0cwAAAAAAAAABAAAACAAACAAAAAAUc3RzcwAAAAAAAAABAAAAAQAAABxz" +
		"dHNjAAAAAAAAAAEAAAABAAAACAAAAAEAAAA0c3RzegAAAAAAAAAAAAAACAAAApUAAAAKAAAACgAAAAoAAAAKAAAACgAAAAoAAAAK" +
		"AAAAFHN0Y28AAAAAAAAAAQAAA3MAAABhdWR0YQAAAFltZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAA" +
		"ACxpbHN0AAAAJKl0b28AAAAcZGF0YQAAAAEAAAAATGF2ZjYyLjMuMTAwAAAACGZyZWUAAALjbWRhdAAAAnAGBf//bNxF6b3m2Ui3" +
		"lizYINkj7u94MjY0IC0gY29yZSAxNjUgcjMyMjIgYjM1NjA1YSAtIEguMjY0L01QRUctNCBBVkMgY29kZWMgLSBDb3B5bGVmdCAy" +
		"MDAzLTIwMjUgLSBodHRwOi8vd3d3LnZpZGVvbGFuLm9yZy94MjY0Lmh0bWwgLSBvcHRpb25zOiBjYWJhYz0wIHJlZj0zIGRlYmxv" +
		"Y2s9MTowOjAgYW5hbHlzZT0weDE6MHgxMTEgbWU9aGV4IHN1Ym1lPTcgcHN5PTEgcHN5X3JkPTEuMDA6MC4wMCBtaXhlZF9yZWY9" +
		"MSBtZV9yYW5nZT0xNiBjaHJvbWFfbWU9MSB0cmVsbGlzPTEgOHg4ZGN0PTAgY3FtPTAgZGVhZHpvbmU9MjEsMTEgZmFzdF9wc2tp" +
		"cD0xIGNocm9tYV9xcF9vZmZzZXQ9LTIgdGhyZWFkcz0xIGxvb2thaGVhZF90aHJlYWRzPTEgc2xpY2VkX3RocmVhZHM9MCBucj0w" +
		"IGRlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJmcmFtZXM9MCB3ZWln" +
		"aHRwPTAga2V5aW50PTI1MCBrZXlpbnRfbWluPTggc2NlbmVjdXQ9NDAgaW50cmFfcmVmcmVzaD0wIHJjX2xvb2thaGVhZD00MCBy" +
		"Yz1jcmYgbWJ0cmVlPTEgY3JmPTIzLjAgcWNvbXA9MC42MCBxcG1pbj0wIHFwbWF4PTY5IHFwc3RlcD00IGlwX3JhdGlvPTEuNDAg" +
		"YXE9MToxLjAwAIAAAAAdZYiEBDxGKAAIb8cAASEY4AAnzScnJ111111114AAAAAGQZo4CHjYAAAABkGaVAIeNgAAAAZBmmAQ8bAA" +
		"AAAGQZqAEPGwAAAABkGaoD/GwAAAAAZBmsA/xsAAAAAGQZrgO8bA",
	"tiny.webm":
		"GkXfo59ChoEBQveBAULygQRC84EIQoKEd2VibUKHgQJChYECGFOAZwEAAAAAAAKsEU2bdLpNu4tTq4QVSalmU6yBoU27i1OrhBZU" +
		"rmtTrIHWTbuMU6uEElTDZ1OsggEjTbuMU6uEHFO7a1OsggKW7AEAAAAAAABZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAVSalmsCrXsYMPQkBNgIxM" +
		"YXZmNjIuMy4xMDBXQYxMYXZmNjIuMy4xMDBEiYhAj0AAAAAAABZUrmvIrgEAAAAAAAA/14EBc8WIoASIIBqrDuacgQAitZyDdW5k" +
		"iIEAhoVWX1ZQOIOBASPjg4QHc1lA4JCwgUC6gTCagQJVsIRVuYEBElTDZ/tzc59jwIBnyJlFo4dFTkNPREVSRIeMTGF2ZjYyLjMu" +
		"MTAwc3PWY8CLY8WIoASIIBqrDuZnyKFFo4dFTkNPREVSRIeUTGF2YzYyLjExLjEwMCBsaWJ2cHhnyKFFo4hEVVJBVElPTkSHkzAw" +
		"OjAwOjAxLjAwMDAwMDAwMAAfQ7Z1QO3ngQCjwYEAAICQAwCdASpAADAAAEcIhYWIhYSIAgICdaoD+AP6Agc7eeLPMx5eAP72vgf/" +
		"alVlWyv/2pZ/+HH1GFB/4X8Ao5aBAH0A0QEAARAQABgAGFgv9AAIjAAAo5aBAPoA0QEAARAQABgAGFgv9AAIjAAAo5aBAXcA0QEA" +
		"ARAQABgAGFgv9AAIjAAAo5aBAfQA0QEAARAQABgAGFgv9AAIjAAAo5aBAnEA0QEAARAQABgAGFgv9AAIjAAAo5aBAu4A0QEAARAQ" +
		"ABgAGFgv9AAIjAAAo5WBA2sAsQEAARAQFGAAYWC/0AAiMAAcU7trkbuPs4EAt4r3gQHxggGj8IED",
	"tiny.mp3":
		"SUQzBAAAAAAAIlRTU0UAAAAOAAADTGF2ZjYyLjMuMTAwAAAAAAAAAAAAAAD/4zjAAAAAAAAAAAAASW5mbwAAAA8AAAAQAAAFWAA1" +
		"NTU1NTVDQ0NDQ0NQUFBQUFBeXl5eXl5ra2tra2treXl5eXl5hoaGhoaGlJSUlJSUoaGhoaGhoa+vr6+vr7y8vLy8vMrKysrKytfX" +
		"19fX19fl5eXl5eXy8vLy8vL///////8AAAAATGF2YzYyLjExAAAAAAAAAAAAAAAAJAKAAAAAAAAABVgks3zqAAAAAAAAAAAAAAAA" +
		"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/4xjEAAxIkpR5TwAABAkoAve973ve9KUpSlKUve79/ffvEqny3i3i" +
		"bi5lzVYbEAIBisH3//5T39H+BDnP9ComhzhZxDf8ZUT/4xjECQ7w8pABlFAAKjlCFv8G3g/UD3IAMqIk4B8TAcyOsDvUw98CUAqA" +
		"qKwihFf/kI9HpEPh8Cv+EgaEoSBq///+TQdEDYL/4xjECAyYpkQB1gAAg6YCIAAMDYQgMLYSgMMI9gMY/9gMqQ6AMUIPgMFIKgFA" +
		"LhfMBQAoZFHA9f//99VKgYBMKGMuYNQvOrr/4xjEEArQpjAABrxEDDeF9N9W3M0XBJzC3BOMD4A8oAWTbLrJCrDWFf//94FV0QGF" +
		"okGA+AaYKwIhh5iUnEpI6aZYdZhoAkH/4xjEHwswpjAAB7BIgqgRmBMA0aGAEaJi08X///k7FUDgMEmEDZgKECJ0AhGBgSyEkYCK" +
		"DdEgESDADgwAMAVCAAsiAEECa4b/4xjELQtopjAABv5E+v//+AV5F9QKAMeMNEXOi4MNgOc3sXOTRICvMLUCIIB9DAI0EaOylLIs" +
		"Kv//+GGVqAOOnIYBoDJgdAr/4xjEOgpQpjQABrxExhaivm0xVGZ1oiphOAqGB6BOYDgCxmMBhpgMPxr///izTUFgMCmEC5hZsYtB" +
		"mCWO0ZinDRjXi5GBkDf/4xjESwsgpjQAB7BIgUCgRgDpnjwAKZzNb9X///glbSDJboxoQ0gU6pIw5gZTghOJNIgEUFDDCwSBgLgA" +
		"hUAVDxbLCtf/////4xjEWQrIpjQABvxE//////Sq///4w19dDFkOwFPmeuGDuLaaUFhplIiPmDMCsYE4EpgIAIGAEAAW/Usa/Zr/" +
		"//jTOUVizJj/4xjEaAyIpjQABrxEgiY9QaTKYN4vRolWxGS6JMYKwKZgIgLJ6s2SRViZbbr4KqOIuo3A4A4aBBCAqzDmA4OC8l40" +
		"kALjDFD/4xjEcArgpjgABrxEBzBKAEMB0AsCgDiIABZbCNf/////////9FX///6yHBiQQgC3sDAKCkDAuBQDA0B8DXF9kDJuX8DG" +
		"2HP/4xjEfwogpjgABrxEAwthBBYDYaOBgLAKFh4o7CQCf////9xHjddr/////dNgaYsIo368jNJpxuMpNhe1+lvzAR8DQAKV/1v/" +
		"4xjEkQ0IpjQAAfxA+AiwogUgOQMUSv//x3kkOQmF0lzpt///mhxE3WBCB//6wIQC4EDh//+VAgcDwENEn///mkPNVR40uXP/4xjE" +
		"lww4pkQBVgAA3snJi9q1a7zRKEp1oyMj644gCgAqhxA6WUwlHyUSVTJiYmLuLjp3LWtaasixBXBTshuIvwV0JUxBTUX/4xjEoRhJ" +
		"nowpm2gAMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/4xjEeg6g3nwh" +
		"zAgBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU=",
	"tiny.m4a":
		"AAAAHGZ0eXBNNEEgAAACAE00QSBpc29taXNvMgAAAx5tb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAD6AABAAABAAAAAAAA" +
		"AAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAACSXRy" +
		"YWsAAABcdGtoZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAD6AAAAAAAAAAAAAAAAQEAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAA" +
		"AAAAAAAAAEAAAAAAAAAAAAAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAA+gAAAQAAAEAAAAAAcFtZGlhAAAAIG1kaGQAAAAA" +
		"AAAAAAAAAAAAAB9AAAAjQFXEAAAAAAAtaGRscgAAAAAAAAAAc291bgAAAAAAAAAAAAAAAFNvdW5kSGFuZGxlcgAAAAFsbWluZgAA" +
		"ABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAAEwc3RibAAAAGpzdHNkAAAAAAAAAAEA" +
		"AABabXA0YQAAAAAAAAABAAAAAAAAAAAAAQAQAAAAAB9AAAAAAAA2ZXNkcwAAAAADgICAJQABAASAgIAXQBUAAAAAAENDAABDQwWA" +
		"gIAFFYhW5QAGgICAAQIAAAAgc3R0cwAAAAAAAAACAAAACAAABAAAAAABAAADQAAAABxzdHNjAAAAAAAAAAEAAAABAAAACQAAAAEA" +
		"AAA4c3RzegAAAAAAAAAAAAAACQAAAX8AAAElAAAA7gAAAOEAAAD3AAABAAAAAP0AAAEjAAAA8gAAABRzdGNvAAAAAAAAAAEAAANK" +
		"AAAAGnNncGQBAAAAcm9sbAAAAAIAAAAB//8AAAAcc2JncAAAAAByb2xsAAAAAQAAAAkAAAABAAAAYXVkdGEAAABZbWV0YQAAAAAA" +
		"AAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAsaWxzdAAAACSpdG9vAAAAHGRhdGEAAAABAAAAAExhdmY2Mi4zLjEw" +
		"MAAAAAhmcmVlAAAJhG1kYXTeAgBMYXZjNjIuMTEuMTAwAAIop1tpqLIRV+FZn7fr1cqXUjmcZx7pJJdyIPXvWfXvXfqXrv1L136l" +
		"679S+o91dq91dq95dq/tv2v8b+r/m/s21iuLYri2Yc1Zh0do3R2zcxa12Ns3Y3NOLaN1txryV3Dt7YveXguDAoE0dbszuPo/Gvvy" +
		"m1wat01TtldU81cR0lsHMXJOzta6qxXQ3WevcZ4bbdu13KrjYrjWqzWqzWrDWqzWqzWqWOuNiuNarNarNNGvz6/Pr8+vz6/Pr8+v" +
		"z6/Pr8+vz6/Pr8+vz6/Pr8phlMMSUSUSUSUSUSUSUSUSUSUtXLVy1ctXLVxJRJRJTgpwU4KWrlq5auWrlq5aulllllllllllllll" +
		"llllllllllllllllllllllllllllllllllllllllllllllllllllRo0YGZMmQNGjRgYGBgYGBgYGBgYGBgYGBgYGBgYGBgYGRF3b" +
		"t3veeeeeeeeeeeeeeeeeeeeeeeeeeeeYzgD4ntmxU5ZrJRdmMhKC7MZIUfpn/7f+3td9cSa38X/X9P/p/6/HCcala45/b7f/h/7/" +
		"iHGpJ5z+n7f9v+f8k1d1x5GOpBTSX04jQNFBqDUUUUROJELIhsqWAQ/1zMvzi+sK5xnXC2g8gPQO9HNu7+XayK2RHkQ5CshuYXkK" +
		"yDYmjJgwMDAyaY8stemmPTFr00wYsZemmmPTTXnfKixCwHIWsGJsiF1FFnbKPPXGPT3nPt0vUYfFJ1Sekh6kPW8d/xn8ZqtCzgsY" +
		"Muhq5GplS0MMElLVl7xr3Mr088888888888888888851Tzz/KeeqjyjTffdRZcxN5Y7bbvbvZHupvCIBZ2LR0wbLx3kRbG6opamB" +
		"ga8DAwMS+U886gDzxPo49VQHAOLzrEQ4HY0GUjCQxGz/4rLZ3/f/y+1/jeruXJcklpbfUmft/oKV+u5NARADAQfEvmwvr3+r/+/8" +
		"gn39w/8fBghZZZZCpKllbaqqmh3PyxjTuke4fuP+k62JcKgANI8a8W7FxWmTTigpb/yv/F0KrJ8NjP76Bk+Mwz++gP/GYO++gP/G" +
		"YJ99AP8fAd99Af+PEO+/uD/HwE+/uH/j4C/f3I/xmMn39yP8ZgnP6AZGwvP7yo+PhtPv7qf+HAvtEvvsgD48UO5/QBzME++hWzNm" +
		"YHfQePj8DHthB+BkoWvSXhSpAIAAPtjPNDJRFlyleADcM5hISBWKCkcVOc9TGnj/+r//7vjd7lS847y11BK0vICbBq2fmVNzZ42E" +
		"qHjZ3iV68DMpIypNKjdXPK7H6nLAo5pawZ0AZ0tncrGAF2VzdXNK5uqNKTKubq5pXNJFJESKSIkUkYApQi+WyeeenZOpU5zqE8/N" +
		"zIdBKXP1Vz5xahOpeoYpQhZTBeQUQmkhZRg35+dykVtsYEomVC9QxWv5lUSvJlCFkLlkAIlkQwb5UuFBctioCGZCiW+FENFeDONX" +
		"0EUvJrbGSoK7j9GIlKoWbUrMZuVkNwJbYbFgJJWueADkM5DWSCIU2yd1ztXGeP/63//fVcd2jLlZKvvXG7vetVnAW0/no9F14har" +
		"cwIyBgYHrNInWGNoa2hrdkHjCn2h3xhT9scem6vx8ZaLCNl7Tb1FXtNvtMeoq2G2G2G6htimw2g2jAwMWBkTIHV8UiZjA1GQM7ld" +
		"Qpf3lGnu5IMyDd3hDQsjgqQZZwjoEdn15iaBNGw9y3g8eKskVM0BOLT8KTkg2rZfm+NGqvBrwLM1yxAFShcNe98rNjOBU5cdWwVD" +
		"RmsWUXoXz5rVXsay9kYzu7iGinmMW6CvZerzuJTCmG1iuG5eCy3K2RCpcGa0YxIYSwVLJc8A3DOYSEskFQoqlK/eku/H/+f//9qK" +
		"yXV7a8aZcTOsuXzYmcnSRu6auyR4bcKh6nNMEzaZVjqsqrSy/pBkKqdDbJh0g462TxLjMqeaIYqFBWWudm52b23NzrW2tba1tos6" +
		"LGixpsYl8l8kokoJQZgmbDD7IubqjgSlhqHFzYVj/4ottEbStafLojwqjhtRG9ZQhwIzsLbaLrRnZRo4bY5ryVIqW8kBIs3kqIF6" +
		"C2P+Y1qlqHMaspJUuWsQEsoZrNRz6YKtvDcvcnYKNZRcVbV2zpL2RyVcxzq5Xrc2rTvX76NJuga3zvbnCFwhu2siGubGEsmWwVLj" +
		"YbsVEqLUYrngAN4zmEQ2FY4KRTXKF+NtL9f/1f//HBWElJvVSl5et3d70CZWFX5lf2nShQV6zzz2nbZbfdfXz3a4TJUk194XWUJk" +
		"qvbizLXA2VdBrdLfAB6rq6rx2Xq9bq6bU6qxsrGyw4JMrDAmknBChDBCoKp9k/N1YTz9U4VPzTrn5jz72paSDJKreTNCxWxGtpwx" +
		"aJC2cWvKJKNbEYaPhcFdPNKK9ohUrWcSUrJFb1zl/i+KlMVi1JQStct4CWcKWa7fglWbCRUVxV7FKNclctqNrYvY51btFp48v1qb" +
		"m919XzI0W4u/F/Wp3hvlLdtYkImrUaDX2KVLkt2mzJTDSbiW9wD0M6xUayMQrq/txKh//F/+LcqbSRJEkIkSQSwDO4fGqkFg4vBr" +
		"sB5/znkwHftZgEBLdODYyhmaUJ5cglf5BTHwEqfTPlfbWCjq2IqNr4Cu8P0iyea9yah/Xz4E2b6yIeLDqflb1z3+b9IRGy7AdNNw" +
		"jh5adPfN030Z17M3nsqyOW5pbkzKex+ruv6tPTVdX3Xx49NWmvuv6semrTXJf1Y4Vaa5L+ruwq01yX9WOFWnpkv6u5dWnpkv6u7w" +
		"q09PZf1d19WnpRf1dy6tPShnV3eFWnpRf1dy1aelF9fcuq7pqZ1d16tPTUzq7r1aempnV3Xq09NTK+69WPTUyvuvj09NV1fderHp" +
		"q01918enpRdX3X78emrT1d1/V++mq7q7r48engE+M5C0ZhFou98K1+368wkkkiSIkSIkFYqirVSSUUaKouFOkkohQoBoVwaHWsi1" +
		"KaW1SP2RnONbrqH/dN5T0EwqF0jaqnSyRvCmjA5q1mcWa/PNuc5ufK03NuchgytNzbnOaDK1zzbnOaDK1zzbnOaB9rnmdc5oH2ue" +
		"Z1zm3Ptc+V1zm3Ia58rrnNuQ1z5Vuc0CGufKtzm3Ia58rTnNuQ1z5Vs5tyFc+Vpzm3OK58rTnNuca58rTObc4rnytM5tziufK03z" +
		"bnIefK03zbnIYMrTc25yGDK03NuchgytNzbnIYMrTfNuchgytNzbnIYMrTfA",
	"tiny.wav":
		"UklGRhYIAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgATElTVBoAAABJTkZPSVNGVA0AAABMYXZmNjIuMy4xMDAAAGRhdGHQ" +
		"BwAAgYWKjY+PjoqFgHt2cnBwcXV5foSJjY+PjouGgXx3c3BwcXR4fYOIjI+PjoyHgn13c3BwcHN3fYKHjI6Pj4yIg314dHFwcHN3" +
		"fIGGi46Pj42JhH55dXFwcHJ2e4CFio6Pj42KhYB6dXJwcHF1en+EiY2Pj46KhoF7dnJwcHF0eX6DiIyPj46Lh4J8d3NwcHFzeH2D" +
		"iIyPkI+MiIN9eHRxcHBzd3yCh4uOj4+MiIN+eXRxcHBydnuBhoqOj4+NiYR/enVxcHBydXp/hYqNj4+OioWAe3ZycHBxdXl+hImN" +
		"j4+Oi4aBfHdzcHBxdHh9g4iMj4+OjIeCfXdzcHBwc3d8goeMjo+PjIiDfXh0cXBwc3d8gYaLjo+PjYmEfnl1cXBwcnZ7gIWKjo+P" +
		"jYqFgHp1cnBwcXV6f4SJjY+PjoqGgXt2cnBwcXR5foOIjI+PjouHgnx3c3BwcXR4fYKIjI+Pj4yIgn14dHFwcHN3fIKHi46Pj4yI" +
		"g355dHFwcHJ2e4GGio6Pj42JhH96dXFwcHJ1eoCFio2Pj46KhYB7dnJwcHF1eX6EiY2Pj46LhoF8d3NwcHF0eH2DiIyPj46Mh4J9" +
		"d3NwcHBzd32Ch4yOj4+MiIN9eHRxcHBzd3yBhouOj4+NiYR+eXVxcHBydnuAhYqOj4+NioWAenVycHBxdXp/hImNj4+OioaBe3Zy" +
		"cHBxdHl+g4iMj4+Oi4eCfHdzcHBxc3h9g4iMj5CPjIiDfXh0cXBwc3d8goeLjo+PjIiDfnl0cXBwcnZ7gYaKjo+PjYmEf3p1cXBw" +
		"cnV6f4WKjY+PjoqFgHt2cnBwcXV5foSJjY+PjouGgXx3c3BwcXR4fYOIjI+PjoyHgn13c3BwcHN3fIKHjI6Pj4yIg314dHFwcHN3" +
		"fIGGi46Pj42JhH55dXFwcHJ2e4CFio6Pj42KhYB6dXJwcHF1en+EiY2Pj46KhoF7dnJwcHF0eX6DiIyPj46Lh4J8d3NwcHF0eH2C" +
		"iIyPj4+MiIJ9eHRxcHBzd3yCh4uOj4+MiIN+eXRxcHBydnuBhoqOj4+NiYR/enVxcHBydXqAhYqNj4+OioWAe3ZycHBxdXl+hImN" +
		"j4+Oi4aBfHdzcHBxdHh9g4iMj4+OjIeCfXdzcHBwc3d9goeMjo+PjIiDfXh0cXBwc3d8gYaLjo+PjYmEfnl1cXBwcnZ7gIWKjo+P" +
		"jYqFgHp1cnBwcXV6f4SJjY+PjoqGgXt2cnBwcXR5foOIjI+PjouHgnx3c3BwcXN4fYOIjI+Qj4yIg314dHFwcHN3fIKHi46Pj4yI" +
		"g355dHFwcHJ2e4GGio6Pj42JhH96dXFwcHJ1en+Fio2Pj46KhYB7dnJwcHF1eX6EiY2Pj46LhoF8d3NwcHF0eH2DiIyPj46Mh4J9" +
		"d3NwcHBzd3yCh4yOj4+MiIN9eHRxcHBzd3yBhouOj4+NiYR+eXVxcHBydnuAhYqOj4+NioWAenVycHBxdXp/hImNj4+OioaBe3Zy" +
		"cHBxdHl+g4iMj4+Oi4eCfHdzcHBxdHh9goiMj4+PjIiCfXh0cXBwc3d8goeLjo+PjIiDfnl0cXBwcnZ7gYaKjo+PjYmEf3p1cXBw" +
		"cnV6gIWKjY+PjoqFgHt2cnBwcXV5foSJjY+PjouGgXx3c3BwcXR4fYOIjI+PjoyHgn13c3BwcHN3fYKHjI6Pj4yIg314dHFwcHN3" +
		"fIGGi46Pj42JhH55dXFwcHJ2e4CFio6Pj42KhYB6dXJwcHF1en+EiY2Pj46KhoF7dnJwcHF0eX6DiIyPj46Lh4J8d3NwcHFzeH2D" +
		"iIyPkI+MiIN9eHRxcHBzd3yCh4uOj4+MiIN+eXRxcHBydnuBhoqOj4+NiYR/enVxcHBydXp/hYqNj4+OioWAe3ZycHBxdXl+hImN" +
		"j4+Oi4aBfHdzcHBxdHh9g4iMj4+OjIeCfXdzcHBwc3d8goeMjo+PjIiDfXh0cXBwc3d8gYaLjo+PjYmEfnl1cXBwcnZ7gIWKjo+P" +
		"jYqFgHp1cnBwcXV6f4SJjY+PjoqGgXt2cnBwcXR5foOIjI+PjouHgnx3c3BwcXR4fYKIjI+Pj4yIgn14dHFwcHN3fIKHi46Pj4yI" +
		"g355dHFwcHJ2e4GGio6Pj42JhH96dXFwcHJ1eoCFio2Pj46KhYB7dnJwcHF1eX6EiY2Pj46LhoF8d3NwcHF0eH2DiIyPj46Mh4J9" +
		"d3NwcHBzd32Ch4yOj4+MiIN9eHRxcHBzd3yBhouOj4+NiYR+eXVxcHBydnuAhYqOj4+NioWAenVycHBxdXp/hImNj4+OioaBe3Zy" +
		"cHBxdHl+g4iMj4+Oi4eCfHdzcHBxc3h9g4iMj5CPjIiDfXh0cXBwc3d8goeLjo+PjIiDfnl0cXBwcnZ7gYaKjo+PjYmEf3p1cXBw" +
		"cnV6f4WKjY+PjoqFgHt2cnBwcXV5foSJjY+PjouGgXx3c3BwcXR4fYOIjI+PjoyHgn13c3BwcHN3fIKHjI6Pj4yIg314dHFwcHN3" +
		"fIGGi46Pj42JhH55dXFwcHJ2e4CFio6Pj42KhYB6dXJwcHF1en+EiY2Pj46KhoF7dnJwcHF0eX6DiIyPj46Lh4J8d3NwcHF0eH2C" +
		"iIyPj4+MiIJ9eHRxcHBzd3yCh4uOj4+MiIN+eXRxcHBydnuBhoqOj4+NiYR/enVxcHBydXo=",
	"tiny.ogg":
		"T2dnUwACAAAAAAAAAADKYrNrAAAAAJdwkM0BHgF2b3JiaXMAAAAAAUAfAAAAAAAAgFcAAAAAAACZAU9nZ1MAAAAAAAAAAAAAymKz" +
		"awEAAABhM4U3Cz////////////+1A3ZvcmJpcwwAAABMYXZmNjIuMy4xMDABAAAAHwAAAGVuY29kZXI9TGF2YzYyLjExLjEwMCBs" +
		"aWJ2b3JiaXMBBXZvcmJpcxJCQ1YBAAABAAxSFCElGVNKYwiVUlIpBR1jUFtHHWPUOUYhZBBTiEkZpXtPKpVYSsgRUlgpRR1TTFNJ" +
		"lVKWKUUdYxRTSCFT1jFloXMUS4ZJCSVsTa50FkvomWOWMUYdY85aSp1j1jFFHWNSUkmhcxg6ZiVkFDpGxehifDA6laJCKL7H3lLp" +
		"LYWKW4q91xpT6y2EGEtpwQhhc+211dxKasUYY4wxxsXiUyiC0JBVAAABAABABAFCQ1YBAAoAAMJQDEVRgNCQVQBABgCAABRFcRTH" +
		"cRxHkiTLAkJDVgEAQAAAAgAAKI7hKJIjSZJkWZZlWZameZaouaov+64u667t6roOhIasBADIAAAYhiGH3knMkFOQSSYpVcw5CKH1" +
		"DjnlFGTSUsaYYoxRzpBTDDEFMYbQKYUQ1E45pQwiCENInWTOIEs96OBi5zgQGrIiAIgCAACMQYwhxpBzDEoGIXKOScggRM45KZ2U" +
		"TEoorbSWSQktldYi55yUTkompbQWUsuklNZCKwUAAAQ4AAAEWAiFhqwIAKIAABCDkFJIKcSUYk4xh5RSjinHkFLMOcWYcowx6CBU" +
		"zDHIHIRIKcUYc0455iBkDCrmHIQMMgEAAAEOAAABFkKhISsCgDgBAIMkaZqlaaJoaZooeqaoqqIoqqrleabpmaaqeqKpqqaquq6p" +
		"qq5seZ5peqaoqp4pqqqpqq5rqqrriqpqy6ar2rbpqrbsyrJuu7Ks256qyrapurJuqq5tu7Js664s27rkearqmabreqbpuqrr2rLq" +
		"urLtmabriqor26bryrLryratyrKua6bpuqKr2q6purLtyq5tu7Ks+6br6rbqyrquyrLu27au+7KtC7vourauyq6uq7Ks67It67Zs" +
		"20LJ81TVM03X9UzTdVXXtW3VdW1bM03XNV1XlkXVdWXVlXVddWVb90zTdU1XlWXTVWVZlWXddmVXl0XXtW1Vln1ddWVfl23d92VZ" +
		"133TdXVblWXbV2VZ92Vd94VZt33dU1VbN11X103X1X1b131htm3fF11X11XZ1oVVlnXf1n1lmHWdMLqurqu27OuqLOu+ruvGMOu6" +
		"MKy6bfyurQvDq+vGseu+rty+j2rbvvDqtjG8um4cu7Abv+37xrGpqm2brqvrpivrumzrvm/runGMrqvrqiz7uurKvm/ruvDrvi8M" +
		"o+vquirLurDasq/Lui4Mu64bw2rbwu7aunDMsi4Mt+8rx68LQ9W2heHVdaOr28ZvC8PSN3a+AACAAQcAgAATykChISsCgDgBAAYh" +
		"CBVjECrGIIQQUgohpFQxBiFjDkrGHJQQSkkhlNIqxiBkjknIHJMQSmiplNBKKKWlUEpLoZTWUmotptRaDKG0FEpprZTSWmopttRS" +
		"bBVjEDLnpGSOSSiltFZKaSlzTErGoKQOQiqlpNJKSa1lzknJoKPSOUippNJSSam1UEproZTWSkqxpdJKba3FGkppLaTSWkmptdRS" +
		"ba21WiPGIGSMQcmck1JKSamU0lrmnJQOOiqZg5JKKamVklKsmJPSQSglg4xKSaW1kkoroZTWSkqxhVJaa63VmFJLNZSSWkmpxVBK" +
		"a621GlMrNYVQUgultBZKaa21VmtqLbZQQmuhpBZLKjG1FmNtrcUYSmmtpBJbKanFFluNrbVYU0s1lpJibK3V2EotOdZaa0ot1tJS" +
		"jK21mFtMucVYaw0ltBZKaa2U0lpKrcXWWq2hlNZKKrGVklpsrdXYWow1lNJiKSm1kEpsrbVYW2w1ppZibLHVWFKLMcZYc0u11ZRa" +
		"i621WEsrNcYYa2415VIAAMCAAwBAgAlloNCQlQBAFAAAYAxjjEFoFHLMOSmNUs45JyVzDkIIKWXOQQghpc45CKW01DkHoZSUQikp" +
		"pRRbKCWl1losAACgwAEAIMAGTYnFAQoNWQkARAEAIMYoxRiExiClGIPQGKMUYxAqpRhzDkKlFGPOQcgYc85BKRljzkEnJYQQQiml" +
		"hBBCKKWUAgAAChwAAAJs0JRYHKDQkBUBQBQAAGAMYgwxhiB0UjopEYRMSielkRJaCylllkqKJcbMWomtxNhICa2F1jJrJcbSYkat" +
		"xFhiKgAA7MABAOzAQig0ZCUAkAcAQBijFGPOOWcQYsw5CCE0CDHmHIQQKsaccw5CCBVjzjkHIYTOOecghBBC55xzEEIIoYMQQgil" +
		"lNJBCCGEUkrpIIQQQimldBBCCKGUUgoAACpwAAAIsFFkc4KRoEJDVgIAeQAAgDFKOSclpUYpxiCkFFujFGMQUmqtYgxCSq3FWDEG" +
		"IaXWYuwgpNRajLV2EFJqLcZaQ0qtxVhrziGl1mKsNdfUWoy15tx7ai3GWnPOuQAA3AUHALADG0U2JxgJKjRkJQCQBwBAIKQUY4w5" +
		"h5RijDHnnENKMcaYc84pxhhzzjnnFGOMOeecc4wx55xzzjnGmHPOOeecc84556CDkDnnnHPQQeicc845CCF0zjnnHIQQCgAAKnAA" +
		"AAiwUWRzgpGgQkNWAgDhAACAMZRSSimllFJKqKOUUkoppZRSAiGllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWU" +
		"UkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimllFJKKaWUUkoppZRSSimVUkoppZRS" +
		"SimllFJKKaUAIN8KBwD/BxtnWEk6KxwNLjRkJQAQDgAAGMMYhIw5JyWlhjEIpXROSkklNYxBKKVzElJKKYPQWmqlpNJSShmElGIL" +
		"IZWUWgqltFZrKam1lFIoKcUaS0qppdYy5ySkklpLrbaYOQelpNZaaq3FEEJKsbXWUmuxdVJSSa211lptLaSUWmstxtZibCWlllpr" +
		"qcXWWkyptRZbSy3G1mJLrcXYYosxxhoLAOBucACASLBxhpWks8LR4EJDVgIAIQEABDJKOeecgxBCCCFSijHnoIMQQgghREox5pyD" +
		"EEIIIYSMMecghBBCCKGUkDHmHIQQQgghhFI65yCEUEoJpZRSSucchBBCCKWUUkoJIYQQQiillFJKKSGEEEoppZRSSiklhBBCKKWU" +
		"UkoppYQQQiillFJKKaWUEEIopZRSSimllBJCCKGUUkoppZRSQgillFJKKaWUUkooIYRSSimllFJKCSWUUkoppZRSSikhlFJKKaWU" +
		"UkoppQAAgAMHAIAAI+gko8oibDThwgMQAAAAAgACTACBAYKCUQgChBEIAAAAAAAIAPgAAEgKgIiIaOYMDhASFBYYGhweICIkAAAA" +
		"AAAAAAAAAAAABE9nZ1MAAAAfAAAAAAAAymKzawIAAABodW9NIDgUEhQTEhMTExQTExMTExQTExMTFBMTExMTFBIUExIgipUZ81O9" +
		"AoBfTIZAZUAKGamKVqd3pxvYDz80TdNaaw3cSDfSdV3XdV3XdV2VNVjDYY7oiI7o7wSSlpndjVcA8FQBAAAAhBRyaT6lAJaWmX0b" +
		"rwBAVQAAAICQQioDNJKWmd2NVwDwWQUAAAAQiHh7fqUAlpaZ3ckrAPTvKQAAAAAbPvrPApaWmXMnrwDQ/14AAAAANpzCNpaWmd3J" +
		"KwD07xMAAAAAGz63niSSlpndjVcA8FklAAAAkMhoJ1yqlpaZfRuvAEBVAQAAgBRSuB4iLZKWmd2NVwDwVBUAAABIIcVyc0oFlpaZ" +
		"3ckrAOzf6gAAAACwD/ZLBZaWmXMnrwCw/x0AAAAABLtljwOSlpnt5BUA9r8jAAAAAMFub90IlpaZ3ckrAPiuAgAAAADOR/1WAZaW" +
		"mX0brwBgqwIAAACEFLIVuTSWlpl9G68A4KoKAAAAEFLI4kenBpaWmd3JKwD4XQEAAACAcP/+owCSlpnt5BUA+t8zAAAAABtOs30B" +
		"kpaZ7eQVAPrfBwAAAAAbTvWOBJaWmd3JKwD4XQkAAACA8HD6VAGSlpndjVcAcFUVAAAASCFFadGhBZaWmX0brwBgqwoAAACkkCLh" +
		"mFqWlpndySsA+K4SAAAAAOZ5OKQCkpaZ7eQVAPa/YwAAAADB7txdSJaWmXMnrwCw/60BAAAABLtlbwOWlpndySsA7N9qAAAAALD3" +
		"/FUAkpaZ3Y1XAPBUAQAAAIQUcmk+pQCWlpl9G68AQFUAAACAkEIqAzSSlpndjVcA8FkFAAAAEIh4e36lAJaWmd3JKwD07ykAAAAA" +
		"Gz76zwKWlplzJ68A0P9eAAAAADacwjaOlpn3Wq8A0P+eBAAVAJNmoRhWF2JKxbbf+W3e5tf+WU9nZ1MABEAfAAAAAAAAymKzawMA" +
		"AACLzLwAAUZyzpMgL9crAPQfVYcEFAUAnCCs6yKcj/sCHv3V39OTYgco6QFKeoCSHrD4A5ZctnHZxmUbl21ctnHZ65Vo6xVEfT7t" +
		"Z7td",
}

/**
 * Decode every fixture to `dir`. Returns { name: Buffer } so a caller can assert
 * a Range slice against `buf.subarray(start, end + 1)` from the very bytes on disk.
 */
function writeFixtures(dir) {
	const out = {}
	for (const [name, b64] of Object.entries(FIXTURES)) {
		const buf = Buffer.from(b64, 'base64')
		fs.writeFileSync(path.join(dir, name), buf)
		out[name] = buf
	}
	return out
}

module.exports = { FIXTURES, writeFixtures }
